### ISSUE TITLE
Linux GCC 7 & 8 support

### ISSUE THREAD

**Issue by rmottola** [wicknix/Arctic-Fox#55]
On (tested Devuan, Debian and Gentoo) ArcticFox compiles with up to gcc 6.5 . Later compilers compile code, but fail to link.

NetBSD instead is capable of building with gcc 7, so it appears to be some platform specific option, maybe linker related.

**Comment by iDevPro** [comment]
@rmottola "Later compilers compile code, but fail to link." 
With relocation error ?

**Comment by rmottola** [comment]
No, failure is not found symbols:
`92:52.96 /usr/bin/ld: ../../netwerk/base/Unified_cpp_netwerk_base0.o: in function `mozilla::net::Predictor::ParseMetaDataEntry(char const*, char const*, nsIURI**, unsigned int&, unsigned int&, unsigned int&)':
92:52.96 /usr/include/stdlib.h:363: undefined reference to `strtol'
92:52.96 /usr/bin/ld: /usr/include/stdlib.h:363: undefined reference to `strtol'
92:52.96 /usr/bin/ld: /usr/include/stdlib.h:363: undefined reference to `strtol'
92:52.96 /usr/bin/ld: /usr/include/stdlib.h:363: undefined reference to `strtol'
92:52.97 /usr/bin/ld: ../../netwerk/base/Unified_cpp_netwerk_base0.o: in function `mozilla::net::Predictor::LearnForSubresource(nsICacheEntry*, nsIURI*)':
92:52.97 /usr/include/stdlib.h:363: undefined reference to `strtol'
92:52.97 /usr/bin/ld: ../../netwerk/cache2/Unified_cpp_netwerk_cache20.o: in function `mozilla::net::CacheFileIOManager::GetDoomedFile(nsIFile**)':
92:52.97 /home/riccardo/Arctic-Fox/netwerk/cache2/CacheFileIOManager.cpp:3424: undefined reference to `srand'
....
`
(and many more)

**Comment by rmottola** [comment]
Finally fixed, I can compile up with gcc 10.
